//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.28 at 02:40:28 PM CEST 
//


package org.easetech.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AttributeFormDefaultValues.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AttributeFormDefaultValues">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="qualified"/>
 *     &lt;enumeration value="unqualified"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AttributeFormDefaultValues")
@XmlEnum
public enum AttributeFormDefaultValues {


    /**
     * If the value is qualified, attributes from the target namespace must be qualified with the namespace prefix.
     * 
     */
    @XmlEnumValue("qualified")
    QUALIFIED("qualified"),

    /**
     * DEFAULT.If the value is unqualified, attributes from the target namespace are not required to be qualified with the namespace prefix.
     * 
     */
    @XmlEnumValue("unqualified")
    UNQUALIFIED("unqualified");
    private final String value;

    AttributeFormDefaultValues(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AttributeFormDefaultValues fromValue(String v) {
        for (AttributeFormDefaultValues c: AttributeFormDefaultValues.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
